version: '3'
services:
  proxy:
    image: nginx:alpine
    build:
      context: ..
      dockerfile: ./prod/Dockerfile-nginx
    ports:
      - ${WEB_PORT}

  php:
    image: icanmake-api-php-fpm
    build:
      context: ..
      dockerfile: ./prod/Dockerfile

  postgres:
    image: postgres:16.0-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}